
name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Production branch
    paths-ignore:
      - 'README.md'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/django-todo
  RDS_URL: ${{ secrets.RDS_DATABASE_URL }}
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: prod-${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            DATABASE_URL=${{ env.RDS_URL }}
            SECRET_KEY=${{ env.SECRET_KEY }}

    #   - name: Clone ArgoCD repository
    #     uses: actions/checkout@v3
    #     with:
    #       repository: Haze-me/argocd
    #       token: ${{ secrets.CHECKOUT_TOKEN }#}
    #       path: tescomp

    #   - name: Update ArgoCD deployment.yaml
    #     run: |
    #       sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|g" ninety/ninety/django-auth.yaml

    #   - name: Commit and push changes to ArgoCD repo
    #     run: |
    #       cd tescomp
    #       git config --global user.email "chriscrsov@gmail.com"
    #       git config --global user.name "chriscrsov"
    #       git add tescomp/django-auth.yaml
    #       git commit -m "Update image tag to $IMAGE_TAG"
    #       git push